# Generated by Django 4.0 on 2025-01-21 18:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0004_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 21, 18, 10, 46, 370385, tzinfo=utc)),
        ),
    ]
