# Generated by Django 4.0 on 2025-01-26 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0005_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 26, 15, 14, 40, 292692, tzinfo=utc)),
        ),
    ]
