# Generated by Django 5.1.4 on 2025-01-19 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 1, 19, 7, 38, 35, 976523, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
